### ISSUE TITLE
Missing NAV links

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/www.isotc154.org#4]
We wanted the navigation links:

In `_config.yml`:
```yaml
nav:
  home:
    url: /
    title: Home
  about:
    url: /about
    title: About ISO/TC 154
  faq:
    url: /faq
    title: FAQ
  standards:
    url: /standards
    title: Standards
```

But only the "About" is being shown. We need this to be fixed ASAP. Thanks!

ping @strogonoff
